Log "================================="
Log "パスワード変更"
Log "passwordEdit"
Log "================================="

wait 2

Log "■メニュー"
Tap  (Image:"menu_btn", WaitFor:10)

Log "■パスワード変更"
Tap "Menu_passwordEdit_Link"

//パスワード変更（トップ）画面遷移チェック
If ImageFound(10,"passwordEdit_word") then 
	//検出
	Log "パスワード変更（トップ）画面遷移チェック：OK"
Else
	//未検出
	LogError "パスワード変更（トップ）画面遷移チェック：NG"
End if

Log "■パスワード入力チェック"
passwordEdit_check
